// Code generated by mockery v2.23.1. DO NOT EDIT.

package objaws

import (
	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	mock "github.com/stretchr/testify/mock"
)

// MockOptionFn is an autogenerated mock type for the OptionFn type
type MockOptionFn struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockOptionFn) Execute(_a0 *s3.Options) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewMockOptionFn interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockOptionFn creates a new instance of MockOptionFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockOptionFn(t mockConstructorTestingTNewMockOptionFn) *MockOptionFn {
	mock := &MockOptionFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
